name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: '5.x'

      - name: Install Dependencies
        run: |
          dotnet restore
          dotnet tool restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Lint
        run: dotnet format --verify-no-changes

      - name: Test
        run:  dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Package
        run: dotnet pack --configuration Release --no-build
