name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5'

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Lint
        run: dotnet format --check

      - name: Test
        run:  dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Package
        run: dotnet pack --configuration Release

  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dotnet-version: [5, 6]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{ matrix.dotnet-version }}'

      - name: Test
        run:  dotnet test --configuration Release
